### ISSUE TITLE
Can this plugin handle nested templates?

### ISSUE THREAD

**Issue by rowild** [trofima/rollup-plugin-ejs#16]
Is sth like this possible?

```html
<body>
	<h1>Welcome to rollup</h1>
	<%- include shared/SVGs.ejs %>
</body>
```

Currently i get an error "Not found"

```bash
[!] (plugin ejs) Error: Could not find the include file "shared/SVGs.ejs"
src/templates/index.ejs
Error: Could not find the include file "shared/SVGs.ejs"
    at getIncludePath (/Volumes/_III_/Z_WWW/rollup-test/node_modules/ejs/lib/ejs.js:165:13)
    at includeSource (/Volumes/_III_/Z_WWW/rollup-test/node_modules/ejs/lib/ejs.js:309:17)
    at /Volumes/_III_/Z_WWW/rollup-test/node_modules/ejs/lib/ejs.js:745:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/Volumes/_III_/Z_WWW/rollup-test/node_modules/ejs/lib/ejs.js:721:15)
    at Template.compile (/Volumes/_III_/Z_WWW/rollup-test/node_modules/ejs/lib/ejs.js:574:12)
    at Object.compile (/Volumes/_III_/Z_WWW/rollup-test/node_modules/ejs/lib/ejs.js:392:16)
    at Object.transform (/Volumes/_III_/Z_WWW/rollup-test/node_modules/rollup-plugin-ejs/dist/rollup-plugin-ejs.js:55:32)
    at /Volumes/_III_/Z_WWW/rollup-test/node_modules/rollup/dist/shared/rollup.js:20218:25
 ```

**Comment by trofima** [comment]
sorry for the late response. 
the answer is no. 
see https://ejs.co/ 
Client-side support -> Caveats section.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/1436182/173636579-a5dfaa69-7bbe-456d-87f5-b5b3b065c669.png">

so basically you can try to pass that third argument and try it out.
